server:
  port: 8080
  servlet:
    context-path: /users

spring:
  application:
    name: users
  datasource:
    url: jdbc:mysql://localhost:3306/bootvue?useSSL=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 980526
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity